fix for docker-compose

diff --git a/bin/warden b/bin/warden
--- a/bin/warden
+++ b/bin/warden
@@ -15,16 +15,16 @@ readonly WARDEN_DIR="$(
 source "${WARDEN_DIR}/utils/core.sh"
 source "${WARDEN_DIR}/utils/env.sh"
 
-## verify docker-compose is installed
-if ! which docker-compose >/dev/null; then
-  fatal "docker-compose could not be found; please install and try again."
+## verify docker compose is installed
+if ! which docker compose >/dev/null; then
+  fatal "docker compose could not be found; please install and try again."
 fi
 
-## verify docker-compose meets version constraint
+## verify docker compose meets version constraint
 DOCKER_COMPOSE_REQUIRE="1.25.0"
-DOCKER_COMPOSE_VERSION="$(docker-compose --version | grep -oE '[0-9\.]+' | head -n1)"
+DOCKER_COMPOSE_VERSION="$(docker compose --version | grep -oE '[0-9\.]+' | head -n1)"
 if ! test $(version ${DOCKER_COMPOSE_VERSION}) -ge $(version ${DOCKER_COMPOSE_REQUIRE}); then
-  fatal "docker-compose version should be ${DOCKER_COMPOSE_REQUIRE} or higher (${DOCKER_COMPOSE_VERSION} installed)"
+  fatal "docker compose version should be ${DOCKER_COMPOSE_REQUIRE} or higher (${DOCKER_COMPOSE_VERSION} installed)"
 fi
 
 ## define and export global shared directory paths
